# pandas에 유용한 numpy 함수 정리

In [1]:
import numpy as np

### np.r_ - slicing에 유용

여러 array를 하나로 concat하는 역할

In [3]:
np.r_[2:5, 6:10]

array([2, 3, 4, 6, 7, 8, 9])

### .where - 필터링

np.where( 조건식, True 결과, False 결과 )

In [2]:
a = np.arange(10)
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [4]:
np.where(a < 3) # 조건식 결과만 index로 가져올 수도 있음

(array([0, 1, 2]),)

### .isin - SQL의 in

np.isin( input array, 비교 array )

In [13]:
a = [3,5,15]
b = np.arange(10)
np.isin(a, b)

array([ True,  True, False])

이 결과를 df.loc[ ]에 조건으로 활용

### .select

np.select(

### .digitize

데이터를 특정값 기준 group 별로 어떤 처리를 할 때 유용 // pandas의 cut 함수와 유사함

In [30]:
times = np.array(['AM','PM'])
bins = np.digitize([6,11,13,22], bins=[12, 24])

위의 경우, < 12 , 12 <= 24, 24 >  3가지 그룹에 맞게 indexing( bins+1 )

In [31]:
bins

array([0, 0, 1, 1])

In [32]:
times[bins]

array(['AM', 'AM', 'PM', 'PM'], dtype='<U2')